version: 2
jobs:
  build:
    macos:
      xcode: "10.2.0"
    working_directory: ~/sora-ios-sdk
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - restore_cache:
          key: pods-{{ checksum "Podfile.lock" }}
      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            bundle exec pod install
      - run:
          name: Install CocoaPods Dependencies
          command: pods install
      - save_cache:
          key: pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods
      - run:
          name: Build
          command: |
            set -o pipefail && \
            xcodebuild \
              -project 'Sora.xcodeproj' \
              -scheme 'Sora' \
              clean build \
              -sdk iphoneos \
              -destination 'generic/platform=iOS' \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGN_IDENTITY= \
              PROVISIONING_PROFILE= | \
            tee $CIRCLE_ARTIFACTS/xcode_raw.log | \
            xcpretty --color --report junit --output $CIRCLE_TEST_REPORTS/xcode/results.xml

workflows:
  version: 2
  build-and-test:
    jobs:
      - build

